title: "The Breakthrough"
theme: PaperMod
baseURL: "https://thebreakthrough.netlify.app/"

copyright: |
  Made with ❤ by [Ranger](https://github.com/Ranger-NF)

minify:
  disableXML: true

languages:
  en:
    languageName: "English"

taxonomies:
  series: series

params:
  env: production
  keywords: [Blog, Portfolio, PaperMod, About]
  defaultTheme: auto
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: "false"
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hideSummary: false
  showShareButtons: true
  ShareButtons: ["linkedin", "instagram", "x"]

  homeInfoParams:
    Title: Game Developer, casual Programmer;
    Hashtags: "#lovesOSS #IndieGameDeveloper #LinuxUser"
    Content: |
        Heyy fellow human! 👋
        
        I'm **Fahad**, a.k.a. **Ranger**

        
        I love programming things that are enjoyable and useful ✨
    
  socialIcons:
      - name: instagram
        url: https://www.instagram.com/ranger_nf/
      - name: github
        url: "https://github.com/Ranger-NF"
      - name: linkedin
        url: https://www.linkedin.com/in/just-fahad/
      - name: itchio
        url: https://ranger-nf.itch.io/

