theme: PaperMod
baseURL: "https://thebreakthrough.netlify.app/"

copyright: |
  Made with ❤ by [Ranger](https://github.com/Ranger-NF)

minify:
  disableXML: true

languages:
  en:
    languageName: "English"

taxonomies:
  series: series

params:
  env: production
  keywords: [Blog, Portfolio, PaperMod, About]
  defaultTheme: auto
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: "false"
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hideSummary: false
  showShareButtons: true
  ShareButtons: ["linkedin", "instagram", "x"]

  profileMode:
    enabled: true
    title: "Mohammed Fahad" # optional default will be site title
    subtitle: "A student who Love creating projects that are intuitive and fun 🍀"
    imageUrl: "images/ranger_profile.svg" # optional
    imageWidth: 240 # custom size
    imageHeight: 240 # custom size
    buttons:
      - name: Blog Posts
        url: "/posts"
      - name: Projects
        url: https://github.com/Ranger-NF?tab=repositories

  socialIcons:
      - name: instagram
        url: https://www.instagram.com/ranger_nf/
      - name: github
        url: "https://github.com/Ranger-NF"
      - name: linkedin
        url: https://www.linkedin.com/in/just-fahad/
      - name: itchio
        url: https://ranger-nf.itch.io/

